<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <h1>Get video duration</h1>
        <form action="./../src/app.php" method="post" enctype="multipart/form-data">
            <input type="file" name="videoFile[]" multiple id="videoFile" accept="video/mp4,video/x-m4v,video/*"> <br />
            <input type="submit" value="Submit" name="submit" id="submit">
        </form>
        <div>
            <br />
            <br />
            <?php
                use MyApp\App;

                if(
                    isset($_POST['submit']) &&
                    !$_FILES['videoFile']['error'][0]
                ) {
                    $filename = $_FILES['videoFile']['tmp_name'][0];
                    App::getVideoDuration($filename)
                        ->then(function($data){
                            echo '<table>';
                                echo '<thead>';
                                    echo '<tr>';
                                        echo '<td><strong>File</strong></td>';
                                        echo '<td><strong>Size</strong></td>';
                                        echo '<td><strong>Duration</strong></td>';
                                    echo '</tr>';
                                echo '</thead>';
                                echo '<tbody>';
                                    echo '<tr>';
                                        echo '<td>' . $_FILES['videoFile']['name'][0] . '</td>';
                                        echo '<td>' . $_FILES['videoFile']['size'][0]/1024/1024 . ' MB</td>';
                                        echo '<td>' . $data . 's</td>';
                                    echo '</tr>';
                                echo '</tbody>';
                            echo '</table>';
                        }, print_r(...)); 
                }
            ?>
        </div>
        
    </body>
</html>